"""Repository initialisation: `strata init`.

Implements the directory layout in docs/spec/02-repository-format.md §2, the
`.gitattributes` and merge-driver installation in
docs/spec/04-git-integration.md §3, and hook installation in §4.
"""

from __future__ import annotations

import hashlib
import re
from datetime import date
from pathlib import Path

from ulid import ULID

from strata import __version__, gitio
from strata.core import manifest as manifest_mod
from strata.core.commit import StructuredCommit
from strata.core.hooks import HOOK_SCRIPTS, HOOKS_DIR

GITATTRIBUTES = """\
* text=auto eol=lf

events/**/*.ndjson     merge=union    -diff=nodiff
records/records.ndjson merge=strata-records
records/aliases.ndjson merge=union
derived/**             merge=strata-regenerate linguist-generated=true
reports/**             merge=strata-regenerate linguist-generated=true
analysis/results/**    merge=strata-regenerate linguist-generated=true
imports/*/raw/**       -merge -diff
*.svg                  -diff
"""

GITIGNORE = """\
/fulltext/*
!/fulltext/manifest.ndjson
/.strata/cache/
"""

MERGE_DRIVERS = {
    "strata-regenerate": {
        "name": "strata: discard both sides and regenerate",
        "driver": "strata merge-regenerate %O %A %B %P",
    },
    "strata-records": {
        "name": "strata: union-merge records by id",
        "driver": "strata merge-records %O %A %B %P",
    },
}

DIRECTORIES = [
    "protocol/searches",
    "imports",
    "records",
    "events/screen",
    "events/dedup",
    "events/retrieval",
    "events/adjudication",
    "extraction/by-reviewer",
    "extraction/consensus",
    "rob/by-reviewer",
    "analysis/results",
    "derived",
    "reports/manuscript",
    "fulltext",
    ".strata/hooks",
    ".strata/cache",
]


class InitError(Exception):
    pass


def _slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "review"


def _write_protocol_stubs(root: Path, title: str) -> None:
    (root / "protocol" / "question.md").write_text(
        f"# Research question\n\n_{title}_\n\nTODO: PICO(TS) and rationale.\n",
        encoding="utf-8",
    )
    empty_digest = hashlib.sha256(b"").hexdigest()
    (root / "protocol" / "criteria.yaml").write_text(
        f'version: 1\ndigest: "sha256:{empty_digest}"\ncriteria: []\n',
        encoding="utf-8",
    )
    (root / "protocol" / "moderators.yaml").write_text("moderators: []\n", encoding="utf-8")
    (root / "protocol" / "outcomes.yaml").write_text("outcomes: []\n", encoding="utf-8")
    (root / "protocol" / "amendments.md").write_text(
        "# Protocol amendments\n\n_Generated by `strata`. Do not edit by hand._\n",
        encoding="utf-8",
    )


def _write_derived_stubs(root: Path) -> None:
    (root / "derived" / "pool.tsv").write_text(
        "record_id\ttiab\tfulltext\tstale\tyear\tfirst_author\ttitle\tjournal\tdoi\n",
        encoding="utf-8",
    )
    (root / "derived" / "conflicts.tsv").write_text(
        "record_id\tstage\topinions\tcriteria_cited\tfirst_seen\ttitle\n", encoding="utf-8"
    )
    (root / "derived" / "stale.tsv").write_text(
        "record_id\tstage\tprior_decision\tprior_criteria\treason\tsince_version\ttitle\n",
        encoding="utf-8",
    )
    (root / "derived" / "counts.json").write_text("{}\n", encoding="utf-8")
    (root / "derived" / "irr.json").write_text("{}\n", encoding="utf-8")


def init_repository(
    root: Path,
    *,
    title: str,
    actor_handle: str,
    actor_name: str,
    actor_email: str | None = None,
    remote: str | None = None,
    slug: str | None = None,
) -> Path:
    if root.exists() and any(root.iterdir()):
        raise InitError(f"{root} is not empty")
    root.mkdir(parents=True, exist_ok=True)

    for rel in DIRECTORIES:
        (root / rel).mkdir(parents=True, exist_ok=True)

    resolved_slug = slug or _slugify(title)
    project_id = f"prj_{ULID()!s}".lower()
    doc = manifest_mod.build_initial_manifest(
        project_id=project_id,
        title=title,
        slug=resolved_slug,
        created=date.today().isoformat(),
        actor_handle=actor_handle,
        actor_name=actor_name,
        actor_email=actor_email,
    )
    manifest_mod.write_manifest(root, doc)

    (root / ".strata" / "schema-version").write_text("1\n", encoding="utf-8")
    (root / "records" / "records.ndjson").write_text("", encoding="utf-8")
    (root / "records" / "aliases.ndjson").write_text("", encoding="utf-8")
    _write_protocol_stubs(root, title)
    _write_derived_stubs(root)

    (root / ".gitattributes").write_text(GITATTRIBUTES, encoding="utf-8")
    (root / ".gitignore").write_text(GITIGNORE, encoding="utf-8")

    for name, script in HOOK_SCRIPTS.items():
        hook_path = root / HOOKS_DIR / name
        hook_path.write_text(script, encoding="utf-8")
        hook_path.chmod(0o755)

    gitio.init(root)
    gitio.set_config(root, "user.name", actor_name)
    gitio.set_config(root, "user.email", actor_email or f"{actor_handle}@users.noreply.local")
    gitio.set_config(root, "core.hooksPath", HOOKS_DIR)
    for driver_name, cfg in MERGE_DRIVERS.items():
        gitio.set_config(root, f"merge.{driver_name}.name", cfg["name"])
        gitio.set_config(root, f"merge.{driver_name}.driver", cfg["driver"])
    if remote:
        gitio.run(["remote", "add", "origin", remote], cwd=root)

    gitio.add_all(root)
    initial_commit = StructuredCommit(
        op="init",
        scope=None,
        summary=f"initialise {resolved_slug}",
        body=f"Created by strata {__version__}.",
        trailers={"Op": "init", "Actor": actor_handle, "Schema-Version": "1"},
    )
    gitio.commit(root, initial_commit.message())
    return root
