"""Blocking: candidate-pair generation for deduplication.

Implements openspec:deduplication#blocking. All-pairs comparison is
O(n^2) and infeasible at 50,000 records, so candidate pairs are generated by
blocking: two records are compared only if they share at least one block key.
Pure functions, no I/O (openspec:architecture#the-fold-is-pure).
"""

from __future__ import annotations

import hashlib
import random
import zlib
from dataclasses import dataclass, field
from itertools import combinations
from typing import Any

from strata.core.ids import (
    normalise_author_family,
    normalise_doi,
    normalise_journal,
    normalise_pages,
    normalise_pmid,
    normalise_title,
    normalise_year,
)

MAX_BLOCK_SIZE = 2000

_SHINGLE_SIZE = 3
_NUM_PERMUTATIONS = 128
_NUM_BANDS = 32
_ROWS_PER_BAND = _NUM_PERMUTATIONS // _NUM_BANDS
_MERSENNE_PRIME = (1 << 61) - 1
# A fixed seed, not a random one: the MinHash coefficients must be identical
# across every run/platform (openspec:canonical-serialisation's byte-
# identity requirement extends in spirit to "the same two records always
# block together"), so this is generated once, deterministically, and is
# unrelated to Python's per-process-randomised `hash()`/`PYTHONHASHSEED`.
_MINHASH_SEED = 0x5354_5241_5441


def _generate_coefficients(seed: int, count: int) -> list[tuple[int, int]]:
    rng = random.Random(seed)
    return [
        (rng.randrange(1, _MERSENNE_PRIME), rng.randrange(0, _MERSENNE_PRIME)) for _ in range(count)
    ]


_COEFFICIENTS = _generate_coefficients(_MINHASH_SEED, _NUM_PERMUTATIONS)


def _shingles(text: str) -> set[str]:
    if len(text) < _SHINGLE_SIZE:
        return {text} if text else set()
    return {text[i : i + _SHINGLE_SIZE] for i in range(len(text) - _SHINGLE_SIZE + 1)}


def minhash_signature(text: str) -> tuple[int, ...] | None:
    """A 128-permutation MinHash signature over character 3-grams, or `None` for empty text.

    `zlib.crc32` gives each shingle a deterministic, platform-stable integer
    (unlike Python's randomised `str.__hash__`) that the fixed universal-hash
    coefficients in `_COEFFICIENTS` then permute.
    """
    shingles = _shingles(text)
    if not shingles:
        return None
    shingle_hashes = [zlib.crc32(s.encode("utf-8")) for s in shingles]
    return tuple(
        min((a * h + b) % _MERSENNE_PRIME for h in shingle_hashes) for a, b in _COEFFICIENTS
    )


def lsh_bands(signature: tuple[int, ...]) -> list[str]:
    """32 band keys of 4 rows each (openspec:deduplication#blocking's ~0.8-Jaccard tuning)."""
    bands = []
    for band_index in range(_NUM_BANDS):
        start = band_index * _ROWS_PER_BAND
        chunk = signature[start : start + _ROWS_PER_BAND]
        digest = hashlib.sha256(",".join(map(str, chunk)).encode("utf-8")).hexdigest()[:16]
        bands.append(f"{band_index}:{digest}")
    return bands


def _first_author_key(record: dict[str, Any]) -> str:
    authors = record.get("author") or []
    if not authors:
        return ""
    first = authors[0]
    name = first.get("family") or first.get("literal") if isinstance(first, dict) else first
    stripped, _unstripped = normalise_author_family(name)
    return stripped


@dataclass(frozen=True)
class RecordBlockKeys:
    """The block key values one record contributes to (openspec:deduplication#blocking's six keys).

    `simple` holds the five single-valued keys (`doi`, `pmid`, `title-prefix`,
    `author-year-vol`, `first-page`; a key is absent when the record lacks
    the fields it needs). `title_lsh_bands` holds the LSH band keys, since a
    record can fall into several bands' buckets at once.
    """

    simple: dict[str, str] = field(default_factory=dict)
    title_lsh_bands: list[str] = field(default_factory=list)


def compute_block_keys(record: dict[str, Any]) -> RecordBlockKeys:
    simple: dict[str, str] = {}

    doi = normalise_doi(record.get("DOI"))
    if doi:
        simple["doi"] = doi

    pmid = normalise_pmid(record.get("PMID"))
    if pmid:
        simple["pmid"] = pmid

    title = normalise_title(record.get("title"))
    year = normalise_year(record.get("issued"))
    if title:
        simple["title-prefix"] = f"{title[:12]}|{year if year is not None else ''}"

    # `normalise_pages` is "the first integer run of a value", the same
    # transformation a volume number needs; reused rather than duplicated.
    volume = normalise_pages(record.get("volume"))
    first_author = _first_author_key(record)
    if first_author and year is not None and volume:
        simple["author-year-vol"] = f"{first_author}|{year}|{volume}"

    journal = normalise_journal(record.get("container-title"))
    first_page = normalise_pages(record.get("page"))
    if journal and volume and first_page:
        simple["first-page"] = f"{journal}|{volume}|{first_page}"

    title_lsh_bands: list[str] = []
    signature = minhash_signature(title)
    if signature is not None:
        title_lsh_bands = lsh_bands(signature)

    return RecordBlockKeys(simple=simple, title_lsh_bands=title_lsh_bands)


@dataclass(frozen=True)
class BlockingResult:
    """`pairs` are `(id_a, id_b)` with `id_a < id_b`, each sharing at least one block key."""

    pairs: frozenset[tuple[str, str]]
    warnings: list[str] = field(default_factory=list)


def _pairs_from_members(members: list[str]) -> set[tuple[str, str]]:
    return {(a, b) if a < b else (b, a) for a, b in combinations(members, 2)}


def find_candidate_pairs(records: dict[str, dict[str, Any]]) -> BlockingResult:
    """Group `records` (id -> record) into blocks and return every candidate pair.

    A block exceeding `MAX_BLOCK_SIZE` is split by year and a warning is
    recorded (openspec:deduplication#blocking) -- almost always the sign of a parse failure that put
    a
    constant string in a blocked field, not a real 2,000-way tie.
    """
    buckets: dict[tuple[str, str], list[str]] = {}
    for record_id, record in records.items():
        keys = compute_block_keys(record)
        for key_type, value in keys.simple.items():
            buckets.setdefault((key_type, value), []).append(record_id)
        for band in keys.title_lsh_bands:
            buckets.setdefault(("title-lsh", band), []).append(record_id)

    pairs: set[tuple[str, str]] = set()
    warnings: list[str] = []
    for (key_type, value), members in buckets.items():
        if len(members) <= MAX_BLOCK_SIZE:
            pairs |= _pairs_from_members(members)
            continue
        warnings.append(
            f"block {key_type}={value!r} has {len(members)} members "
            f"(over the {MAX_BLOCK_SIZE} cap); split by year"
        )
        by_year: dict[int | None, list[str]] = {}
        for record_id in members:
            year = normalise_year(records[record_id].get("issued"))
            by_year.setdefault(year, []).append(record_id)
        for year_members in by_year.values():
            pairs |= _pairs_from_members(year_members[:MAX_BLOCK_SIZE])

    return BlockingResult(pairs=frozenset(pairs), warnings=warnings)
